INSERT INTO SoccerOrders (OrderID, ProductName, Quantity, Price, OrderProcessed) VALUES ('ORD001', 'Camisola', '25', '750', 'YES');
INSERT INTO SoccerOrders (OrderID, ProductName, Quantity, Price, OrderProcessed) VALUES ('ORD002', 'Calção', '25', '500', 'YES');
INSERT INTO SoccerOrders (OrderID, ProductName, Quantity, Price, OrderProcessed) VALUES ('ORD003', 'Sapatilha (par)', '25', '15', 'YES');
INSERT INTO SoccerOrders (OrderID, ProductName, Quantity, Price, OrderProcessed) VALUES ('ORD004', 'Meias (par)', '25', '150', 'YES');
INSERT INTO SoccerOrders (OrderID, ProductName, Quantity, Price, OrderProcessed) VALUES ('ORD005', 'Bolas de futebol', '100', '5000', 'NO');
INSERT INTO SoccerOrders (OrderID, ProductName, Quantity, Price, OrderProcessed) VALUES ('ORD006', 'Garrafa de água', '500', '400', 'YES');
INSERT INTO SoccerOrders (OrderID, ProductName, Quantity, Price, OrderProcessed) VALUES ('ORD007', 'Apito', '2', '2', 'YES');
INSERT INTO SoccerOrders (OrderID, ProductName, Quantity, Price, OrderProcessed) VALUES ('ORD008', 'Luvas de GR (par)', '5', '50', 'NO');
INSERT INTO SoccerOrders (OrderID, ProductName, Quantity, Price, OrderProcessed) VALUES ('ORD009', 'T-shirt branca', '1500', '4500', 'YES');
INSERT INTO SoccerOrders (OrderID, ProductName, Quantity, Price, OrderProcessed) VALUES ('ORD010', 'Estampagem', '50', '500', 'YES');
INSERT INTO SoccerOrders (OrderID, ProductName, Quantity, Price, OrderProcessed) VALUES ('ORD011', 'Apito', '3', '3', 'YES');
INSERT INTO SoccerOrders (OrderID, ProductName, Quantity, Price, OrderProcessed) VALUES ('ORD012', 'Cachecol', '1000', '10000', 'NO');
INSERT INTO SoccerOrders (OrderID, ProductName, Quantity, Price, OrderProcessed) VALUES ('ORD013', 'Bandeira', '2', '500', 'NO');
INSERT INTO SoccerOrders (OrderID, ProductName, Quantity, Price, OrderProcessed) VALUES ('ORD014', 'Cronometro', '2', '50', 'YES');
INSERT INTO SoccerOrders (OrderID, ProductName, Quantity, Price, OrderProcessed) VALUES ('ORD015', 'Pinos', '50', '500', 'YES');
INSERT INTO SoccerOrders (OrderID, ProductName, Quantity, Price, OrderProcessed) VALUES ('ORD016', 'Toalhas', '25', '1250', 'NO');
INSERT INTO SoccerOrders (OrderID, ProductName, Quantity, Price, OrderProcessed) VALUES ('ORD017', 'Chinelos', '25', '250', 'NO');
INSERT INTO SoccerOrders (OrderID, ProductName, Quantity, Price, OrderProcessed) VALUES ('ORD018', 'Alvos', '4', '400', 'NO');
INSERT INTO SoccerOrders (OrderID, ProductName, Quantity, Price, OrderProcessed) VALUES ('ORD019', 'Creme de massagem', '10', '1000', 'NO');
INSERT INTO SoccerOrders (OrderID, ProductName, Quantity, Price, OrderProcessed) VALUES ('ORD020', 'Barreiras', '10', '1000', 'NO');

